server:
  port: 8081

spring:
  application:
    name: auth-service

# Service endpoints
services:
  user:
    url: ${USER_SERVICE_URL:http://user:8084}

jwt:
  secret: ${JWT_SECRET:thisIsAVerySecureSecretKeyThatShouldBeChangedInProduction}
  expiration: 3600000 # 1 hour
