version: '3.8'

services:
  # Search Service
  search-service:
    build: ./search-service
    ports:
      - "8084:8084"  # Changed to use the original port 8084 directly
    environment:
      - SPRING_APPLICATION_NAME=search-service
    networks:
      - search-miw-network

  # History Service
  history-service:
    build: ./history-service
    container_name: history-service
    depends_on:
      history-db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_HOST=history-db
      - MYSQL_PORT=3306
      - MYSQL_DB=history_db
      - MYSQL_USER=history_user
      - MYSQL_PASSWORD=history_password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    ports:
      - "8085:8085"
    networks:
      - search-miw-network

  # History Database
  history-db:
    image: mysql:8.0
    container_name: history-db
    environment:
      - MYSQL_DATABASE=history_db
      - MYSQL_USER=history_user
      - MYSQL_PASSWORD=history_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - history-db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - search-miw-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "history_user", "--password=history_password"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
      
  # User Service
  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      user-db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_HOST=user-db
      - MYSQL_PORT=3306
      - MYSQL_DB=user_db
      - MYSQL_USER=user_service
      - MYSQL_PASSWORD=user_password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    ports:
      - "8086:8086"
    networks:
      - search-miw-network

  # User Database
  user-db:
    image: mysql:8.0
    container_name: user-db
    environment:
      - MYSQL_DATABASE=user_db
      - MYSQL_USER=user_service
      - MYSQL_PASSWORD=user_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - user-db-data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - search-miw-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user_service", "--password=user_password"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Aggregator Service
  aggregator:
    build: ./aggregator
    container_name: aggregator
    depends_on:
      - user-service
      - history-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8087:8087"
    networks:
      - search-miw-network
  
networks:
  search-miw-network:
    driver: bridge

volumes:
  history-db-data:
  user-db-data:
