server:
  port: 8083

spring:
  application:
    name: data-aggregator
  
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      printer:
        enabled: true
    cors:
      allowed-origins: "*"
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allowed-headers: "*"
      max-age: 3600

# Service endpoints
services:
  history:
    url: ${HISTORY_SERVICE_URL:http://history:8082}
  user:
    url: ${USER_SERVICE_URL:http://user:8084}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:thisIsAVerySecureSecretKeyThatShouldBeChangedInProduction}
