server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
        - id: user-service
          uri: http://user-service:8086
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0
            - AuthenticationFilter
        # Search Service routes
        - id: search-service
          uri: http://search-service:8084
          predicates:
            - Path=/api/search/**
          filters:
            - StripPrefix=1
            
        # Search Service API docs
        - id: search-service-docs
          uri: http://search-service:8084
          predicates:
            - Path=/search-docs/**
          filters:
            - RewritePath=/search-docs/(?<segment>.*), /$\{segment}
            
        # History Service API docs
        - id: history-service-docs
          uri: http://history-service:8085
          predicates:
            - Path=/history-docs/**
          filters:
            - RewritePath=/history-docs/(?<segment>.*), /$\{segment}
            
        # User Service API docs
        - id: user-service-docs
          uri: http://user-service:8086
          predicates:
            - Path=/user-docs/**
          filters:
            - RewritePath=/user-docs/(?<segment>.*), /$\{segment}
            
        # Aggregator Service GraphQL UI
        - id: aggregator-service-graphiql
          uri: http://aggregator:8087
          predicates:
            - Path=/aggregator-ui/**
          filters:
            - RewritePath=/aggregator-ui/(?<segment>.*), /$\{segment}
        # Add other services as needed
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

jwt:
  secret: ${JWT_SECRET:veryLongAndSecureSecretKeyForJwtSigningThatShouldBeAtLeast256BitsLong}
  audience: miw-api-clients
  issuer: auth-service

# SpringDoc configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    configUrl: /api-docs/swagger-config
    urls:
      - url: /search-docs/api-docs
        name: Search Service
      - url: /history-docs/api-docs
        name: History Service
      - url: /user-docs/api-docs
        name: User Service
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
