server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://auth:8081}
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
            - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST
            - DedupeResponseHeader=Access-Control-Allow-Credentials, RETAIN_FIRST
            
        # Data Aggregator GraphQL API
        - id: data-aggregator-graphql
          uri: ${DATA_AGGREGATOR_URL:http://data-aggregator:8083}
          predicates:
            - Path=/graphql/**
          filters:
            - StripPrefix=0
            - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST
            - DedupeResponseHeader=Access-Control-Allow-Credentials, RETAIN_FIRST
            
        # Data Aggregator GraphiQL interface (for development)
        - id: data-aggregator-graphiql
          uri: ${DATA_AGGREGATOR_URL:http://data-aggregator:8083}
          predicates:
            - Path=/graphiql
          filters:
            - StripPrefix=0
            
        # Frontend redirect for root path
        - id: root-redirect
          uri: ${FRONTEND_URL:http://frontend:80}
          predicates:
            - Path=/
          filters:
            - RedirectTo=302, /index.html
            
        # Static welcome page for API users
        - id: welcome-page
          uri: no://op
          predicates:
            - Path=/api
          filters:
            - SetPath=/welcome.html
            - SetStatus=200
            - AddResponseHeader=Content-Type, text/html
            - ModifyResponseBody=*/*,*/*,com.searchmiw.gateway.filter.WelcomePageModifier
            
        # Add more routes here for other services
      default-filters:
        - JwtAuthenticationFilter
      # Remove the globalcors configuration since we have it in CorsConfig.java
      # This prevents conflicts between the two configurations

jwt:
  secret: ${JWT_SECRET:thisIsAVerySecureSecretKeyThatShouldBeChangedInProduction}
  expiration: 3600000 # 1 hour
