server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # Search Service routes
        - id: search-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/search/**
          filters:
            - StripPrefix=1
            
        # Search Service API docs
        - id: search-service-docs
          uri: http://localhost:8084
          predicates:
            - Path=/search-docs/**
          filters:
            - RewritePath=/search-docs/(?<segment>.*), /$\{segment}
            
        # History Service API docs
        - id: history-service-docs
          uri: http://localhost:8085
          predicates:
            - Path=/history-docs/**
          filters:
            - RewritePath=/history-docs/(?<segment>.*), /$\{segment}
            
        # User Service API docs
        - id: user-service-docs
          uri: http://localhost:8086
          predicates:
            - Path=/user-docs/**
          filters:
            - RewritePath=/user-docs/(?<segment>.*), /$\{segment}
            
        # Aggregator Service GraphQL UI
        - id: aggregator-service-graphiql
          uri: http://localhost:8087
          predicates:
            - Path=/aggregator-ui/**
          filters:
            - RewritePath=/aggregator-ui/(?<segment>.*), /$\{segment}

# SpringDoc configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    configUrl: /api-docs/swagger-config
    urls:
      - url: /search-docs/api-docs
        name: Search Service
      - url: /history-docs/api-docs
        name: History Service
      - url: /user-docs/api-docs
        name: User Service
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
