server:
  port: 8082

spring:
  application:
    name: history-service
  
  # PostgreSQL Database Configuration (for production)
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/historydb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  # H2 Database Configuration (for development - uncomment if needed)
  # datasource:
  #   url: jdbc:h2:mem:historydb
  #   username: sa
  #   password: password
  #   driver-class-name: org.h2.Driver
  
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: update
    show-sql: true
  
  # H2 Console (for development - uncomment if needed)
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console
  #     settings:
  #       web-allow-others: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:thisIsAVerySecureSecretKeyThatShouldBeChangedInProduction}
