server:
  port: 8083

spring:
  application:
    name: data-aggregator-service

# Service endpoints
services:
  history:
    url: ${HISTORY_SERVICE_URL:http://history-service:8082}
  user:
    url: ${USER_SERVICE_URL:http://user-service:8084}
